import type { Metadata } from "next";
import { cookies } from "next/headers";
import "./styles/globals.css";
import "./styles/themes/light.css";
import "./styles/themes/dark.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme');
  const initialTheme = theme?.value === 'light' ? 'light' : 'dark';

  return (
    // Set the data-theme attribute based on the server-read cookie
    <html lang="en" data-theme={initialTheme} suppressHydrationWarning>
      <body>
        {children}
      </body>
    </html>
  );
}
