import type { Metadata } from "next";
import "./styles/globals.css";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get('theme');
  const initialTheme = theme?.value === 'light' ? 'light' : 'dark';

  const setTheme = initialTheme === 'dark'
    ? "/themes/dark.css"
    : "/themes/light.css";

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href={setTheme} />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
